// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Thermostat

#include "ui.h"
#include "ui_helpers.h"
#include "common_Display.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Header;
void ui_event_Header_Date(lv_event_t * e);
lv_obj_t * ui_Header_Date;
void ui_event_Header_Time(lv_event_t * e);
lv_obj_t * ui_Header_Time;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Arc_Group;
lv_obj_t * ui_Arc1;
lv_obj_t * ui_Temp_Bg;
lv_obj_t * ui_Temp_Num_Bg;
void ui_event_Label_Celsius(lv_event_t * e);
lv_obj_t * ui_Label_Celsius;
void ui_event_ButtonAuto(lv_event_t * e);
lv_obj_t * ui_ButtonAuto;
lv_obj_t * ui_Label1;
void ui_event_ButtonDay(lv_event_t * e);
lv_obj_t * ui_ButtonDay;
lv_obj_t * ui_Label3;
void ui_event_ButtonNight(lv_event_t * e);
lv_obj_t * ui_ButtonNight;
lv_obj_t * ui_Label4;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Header_Date(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_REFRESH) {
       // _ui_label_set_property(ui_Header_Date, _UI_LABEL_PROPERTY_TEXT, currentDate);
    }
}
void ui_event_Header_Time(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_REFRESH) {
       // _ui_label_set_property(ui_Header_Time, _UI_LABEL_PROPERTY_TEXT, currentTime);
    }
}
void ui_event_Label_Celsius(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_PRESSED) {
        CelciusPressed(e);
    }
    if(event_code == LV_EVENT_REFRESH)
    {
        char buf[_UI_TEMPORARY_STRING_BUFFER_SIZE];
        if (currentTemp)
        {
            //lv_snprintf(buf, sizeof(buf), "%s%s%s", "", currentTemp, "°C");
            lv_snprintf(buf, sizeof(buf), "%.1f °C", currentTemp);
            //_ui_arc_set_text_value(ui_Label_Celsius, ui_Label_Celsius, "", "°C");
            lv_label_set_text(ui_Label_Celsius, buf);
        }
    }
}
void ui_event_ButtonAuto(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_ButtonDay, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_ButtonNight, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_ButtonAuto, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        autoFunction(e);
    }
}
void ui_event_ButtonDay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_ButtonAuto, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_ButtonDay, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_ButtonNight, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        dayFunction(e);
    }
}
void ui_event_ButtonNight(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_state_modify(ui_ButtonNight, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_ButtonAuto, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_ButtonDay, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
        nightFunction(e);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
