// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: Thermostat

#ifndef _THERMOSTAT_UI_H
#define _THERMOSTAT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "common_Display.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Header;
void ui_event_Header_Date(lv_event_t * e);
extern lv_obj_t * ui_Header_Date;
void ui_event_Header_Time(lv_event_t * e);
extern lv_obj_t * ui_Header_Time;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Arc_Group;
extern lv_obj_t * ui_Arc1;
extern lv_obj_t * ui_Temp_Bg;
extern lv_obj_t * ui_Temp_Num_Bg;
void ui_event_Label_Celsius(lv_event_t * e);
extern lv_obj_t * ui_Label_Celsius;
void ui_event_ButtonAuto(lv_event_t * e);
extern lv_obj_t * ui_ButtonAuto;
extern lv_obj_t * ui_Label1;
void ui_event_ButtonDay(lv_event_t * e);
extern lv_obj_t * ui_ButtonDay;
extern lv_obj_t * ui_Label3;
void ui_event_ButtonNight(lv_event_t * e);
extern lv_obj_t * ui_ButtonNight;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui____initial_actions0;



LV_FONT_DECLARE(ui_font_Font30);
LV_FONT_DECLARE(ui_font_Number);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
