// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.4
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "common_Display.h"
#include <Arduino.h>

void autoFunction(lv_event_t * e)
{
	// Your code here
	//
	LV_LOG("Auto func\n");
	//Hc1_Mode = "auto";
	
}

void dayFunction(lv_event_t * e)
{
	// Your code here
	LV_LOG("Day func\n");
	//Hc1_Mode = "day";
}

void nightFunction(lv_event_t * e)
{
	// Your code here
	LV_LOG("Night func\n");
	//Hc1_Mode = "night";
}

void ButtonClickedFunc(lv_event_t * e)
{
	
}

void CelciusPressed(lv_event_t * e)
{
	// Your code here
}